#!/usr/bin/env bash
# RT-001: generate local test secrets into gitignored .rt001/secrets.env
# Safe random placeholders only — never commit this file.
# Production readiness: NOT READY.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RT001_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME="$ROOT/.rt001"
OUT="$RUNTIME/secrets.env"
EXAMPLE="$RT001_DIR/.env.example"

mkdir -p "$RUNTIME"

rand_hex() {
  # Prefer openssl; fall back to /dev/urandom.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${1:-16}"
  else
    head -c "${1:-16}" /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c "$(( ${1:-16} * 2 ))"
    echo
  fi
}

MONGO_PORT="${RT001_MONGO_PORT:-27018}"
MINIO_USER="rt001$(rand_hex 4 | tr -d '\n')"
MINIO_PASS="rt001-$(rand_hex 12 | tr -d '\n')"
BUCKET="stratex-rt001"

{
  echo "# Generated by engineering/rt001/generate_local_secrets.sh"
  echo "# DO NOT COMMIT. Gitignored under .rt001/"
  echo "# Production readiness: NOT READY"
  echo "# Base SHA: 0c09b0cf44fb133852ddbb9ce96cea2e137ade6d"
  echo
  echo "RT001_MONGO_PORT=${MONGO_PORT}"
  echo "MONGO_URL=mongodb://127.0.0.1:${MONGO_PORT}/?replicaSet=rs0&directConnection=true"
  echo "DB_NAME=stratex_rt001"
  echo "RT001_MONGO_REPLICA_SET=rs0"
  echo
  echo "RT001_MINIO_API_PORT=9000"
  echo "RT001_MINIO_CONSOLE_PORT=9001"
  echo "RT001_MINIO_ROOT_USER=${MINIO_USER}"
  echo "RT001_MINIO_ROOT_PASSWORD=${MINIO_PASS}"
  echo "RT001_MINIO_BUCKET=${BUCKET}"
  echo "RT001_S3_ENDPOINT=http://127.0.0.1:9000"
  echo "RT001_S3_ACCESS_KEY=${MINIO_USER}"
  echo "RT001_S3_SECRET_KEY=${MINIO_PASS}"
  echo "RT001_S3_BUCKET=${BUCKET}"
  echo "RT001_S3_REGION=us-east-1"
  echo
  echo "NEXTGEN_STORAGE_ROOT=${RUNTIME}/nextgen_storage"
  echo "RT001_PRODUCTION_READY=false"
} > "$OUT"

chmod 600 "$OUT"
echo "[OK] wrote local secrets to ${OUT} (gitignored)"
echo "  - Example template remains at ${EXAMPLE} (placeholders only)"
exit 0
